### ISSUE TITLE
Module resolution fails for index.ts exports within .motia/compiled

### ISSUE THREAD

**Issue by truthtaicom** [MotiaDev/motia#1092]
### Environment

Node 23

### Steps to Reproduce

1. Create a directory named `auth`.
2. Inside the auth directory, create two files: `index.ts` and `login.ts`.
3. In `index.ts`, export the contents of the login file:

```
export * from './login';
```
4. Attempt to import a method from the folder-level export in a separate file:

```
import { loginMethod } from './auth';
```
5. `npm run dev`

### Expected Behavior

The TypeScript module should resolve correctly, allowing the import of methods from the directory's index file without compilation or runtime errors.

### Actual Behavior

The application fails with a COMPILATION Error. The ESM loader is unable to resolve the module path for the compiled directory, specifically looking for auth.js instead of identifying the directory index.

### Relevant Logs/Console Output

```shell
Error running TypeScript module: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/xxx/.motia/compiled/src/auth.js' imported from /Users/xxx/.motia/compiled/process-auth.step.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:780:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:704:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:687:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:305:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:137:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:////Users/xxx/.motia/compiled/src/auth.js'
}
```

### Motia Version

v0.17.0-beta.180

### Additional Context

[v0.16.1-beta.179...v0.17.0-beta.180](https://github.com/MotiaDev/motia/compare/v0.16.1-beta.179...v0.17.0-beta.180)

It is working with `v0.16.1-beta.179` but `v0.17.0-beta.180`

**Comment by truthtaicom** [comment]
Hi @rohitg00  @ytallo ,
do you have any update?

**Comment by ytallo** [comment]
Closing as part of the Motia becomes iii now. This issue references the legacy motia package/CLI/branding, which has been removed from the repository. If the underlying problem still reproduces against the current iii codebase, please open a new issue with updated reproduction steps referencing the current tooling. Thanks for the original report!

Migration guides:
- Node.js: https://iii.dev/docs/changelog/0-11-0/migrating-from-motia-js
- Python: https://iii.dev/docs/changelog/0-11-0/migrating-from-motia-py
